# Generated by Django 5.2.7 on 2025-12-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_created_at_event_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('neon', 'Neon'), ('classic', 'Classic')], default='minimal', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
