# Generated by Django 5.2.7 on 2025-12-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_event_theme_alter_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='theme',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
