# Generated by Django 5.2.7 on 2025-12-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_event_theme_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remaining_seconds',
            field=models.BigIntegerField(blank=True, help_text='Remaining seconds when paused. Null = running.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('finished', 'Finished')], default='running', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
